# docker-compose.yml

version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: ui/backend/Dockerfile
    container_name: options_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./ui/frontend/react-app
      dockerfile: Dockerfile
    container_name: options_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
